version: 2

cache_key: &cache_key
  key: jars-{{ checksum "buildSrc/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

android_config: &android_config
  working_directory: ~/Tickmarks
  docker:
    - image: circleci/android:api-30
  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx1g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

gcloud_config: &gcloud_config
  working_directory: ~/Tickmarks
  docker:
    - image: google/cloud-sdk:latest
  environment:
    TERM: dumb

jobs:
  build:
    <<: *android_config
    steps:
      - checkout

      - restore_cache:
          <<: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - run:
          name: Lint, Detekt and Assemble APK
          command: ./gradlew lintDebug detekt dependencyUpdates assembleDebug assembleDebugAndroidTest
      - run:
          name: Copy Lint Reports
          command: .circleci/store_artifact.sh ".*/build/reports/lint-results-debug.xml" ~/lint-reports/
      - run:
          name: Copy Detekt Reports
          command: .circleci/store_artifact.sh ".*/build/reports/detekt/detekt.xml" ~/detekt-reports/
      - run:
          name: Copy Dependency Reports
          command: .circleci/store_artifact.sh ".*/build/dependencyUpdates/report.txt" ~/dependency-reports/

      - store_artifacts:
          path: ~/lint-reports
      - store_artifacts:
          path: ~/detekt-reports
      - store_artifacts:
          path: ~/dependency-reports

      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build
            - ./**/**/build

  unit_test:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks
      - restore_cache:
          <<: *cache_key

      - run:
          name: Run Tests
          command: ./gradlew test
      - run:
          name: Copy Test Results
          command: .circleci/store_artifact.sh ".*/build/test-results/.*xml" ~/test-results/

      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  instrumented_test:
    <<: *gcloud_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks

      - run:
          name: Setup Google Cloud Auth
          command: .circleci/ftl_setup.sh

      - run:
          name: Test with Firebase Test Lab and download results
          command: |
            .circleci/ftl_test.sh app bookmark/ui ~/instrumented-test-results
            .circleci/ftl_test.sh app bookmark/data ~/instrumented-test-results

      - store_artifacts:
          path: ~/instrumented-test-results
      - store_test_Results:
          path: ~/instrumented-test-results

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - instrumented_test:
          requires:
            - build
