version: 2.1

cache_key: &cache_key
  key: jars-{{ checksum "buildSrc/build.gradle.kts" }}-{{ checksum "buildSrc/src/main/java/Dependencies.kt" }}-{{ checksum "gradle/wrapper/gradle-wrapper.properties" }}

android_config: &android_config
  working_directory: ~/Tickmarks
  docker:
    - image: circleci/android:api-30
  environment:
    TERM: dumb
    JAVA_TOOL_OPTIONS: "-Xmx1g"
    GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dkotlin.incremental=false"

commands:
  reveal_secrets:
    steps:
      - run:
          name: Reveal Secrets
          command: .circleci/reveal_secrets.sh
  hide_secrets:
    steps:
      - run:
          name: Hide Secrets
          command: .circleci/hide_secrets.sh
          when: always

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - restore_cache:
          <<: *cache_key
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies

      - reveal_secrets

      - run:
          name: Assemble APKs
          command: ./gradlew assembleFlank assembleRelease

      - hide_secrets

      - save_cache:
          <<: *cache_key
          paths:
            - ~/.gradle/caches
            - ~/.gradle/wrapper

      - persist_to_workspace:
          root: .
          paths:
            - build
            - ./**/build
            - ./**/**/build
            - .gradle
            - buildSrc/.gradle

  static_analysis:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks
      - restore_cache:
          <<: *cache_key

      - reveal_secrets

      - run:
          name: Run Lint, Detekt and Dependency Updates
          command: ./gradlew lintDebug detekt dependencyUpdates

      - hide_secrets

      - run:
          name: Copy Reports
          command: |
            .circleci/store_artifact.sh ".*/build/reports/lint-results-debug.xml" ~/lint-reports/
            .circleci/store_artifact.sh ".*/build/reports/detekt/detekt.xml" ~/detekt-reports/
            .circleci/store_artifact.sh ".*/build/dependencyUpdates/report.txt" ~/dependency-reports/

      - store_artifacts:
          path: ~/lint-reports
      - store_artifacts:
          path: ~/detekt-reports
      - store_artifacts:
          path: ~/dependency-reports

  unit_test:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks
      - restore_cache:
          <<: *cache_key

      - reveal_secrets

      - run:
          name: Run Unit Tests
          command: ./gradlew testDebugUnitTest

      - hide_secrets

      - run:
          name: Copy Test Results
          command: .circleci/store_artifact.sh ".*/build/test-results/.*xml" ~/test-results/

      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results

  instrumented_test:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks
      - restore_cache:
          <<: *cache_key

      - reveal_secrets

      - run:
          name: Run Instrumented Tests on Firebase
          command: ./gradlew runFlank

      - hide_secrets

      - run:
          name: Copy Test Results
          command: .circleci/store_artifact.sh "./build/fladle/.*xml"  ~/instrumented-test-results

      - store_test_results:
          path: ~/instrumented-test-results
      - store_artifacts:
          path: ~/instrumented-test-results

  deploy:
    <<: *android_config
    steps:
      - checkout
      - attach_workspace:
          at: ~/Tickmarks
      - restore_cache:
          <<: *cache_key

      - reveal_secrets

      - run:
          name: Deploy on Firebase
          command: ./gradlew appDistributionUploadRelease

      - hide_secrets

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - static_analysis:
          requires:
            - build
      - unit_test:
          requires:
            - build
      - instrumented_test:
          requires:
            - build
      - deploy:
          requires:
            - static_analysis
            - unit_test
            - instrumented_test
